apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: downloadstats-api-rule
  namespace: team2001
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: downloadstats-service
    port: 8080
    host: downloadstats
  rules:
    - path: /.*
      methods: ['GET', 'POST']
      mutators: []
      accessStrategies:
        - handler: noop
          config: {}
          # config:
          #   required_scope: ['read', 'write']
