apiVersion: v1
kind: Config
current-context: shoot--kyma--c2aecf0
clusters:
  - name: shoot--kyma--c2aecf0
    cluster:
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5ekNDQWQrZ0F3SUJBZ0lSQU9qSW1TODFqOHM2Y29FTXNQclVJWVl3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpBME1qQXhPVFF4TXpCYUZ3MHpNakEwTWpBeApPVFF4TXpCYU1CVXhFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUUNjZVo2NEFEbGhwMnNGYnVxbFRjZU44UXJhOGNjQUluTksvcDJtbVZyejZkMTgKZnI1WTByZllEdXM4Ynh3U3Vrcmhzam5kNFhNMEFJWU14OEpBcHhlY2ZPZjRqZ0s5YnlUVDZyR2hHZU1nMWtReQpTdzI2R1orR2RrZUMxVGg1WTRqZFV4R2FJVld3bmR4eHByR05kN0hvbVNmNWVsL1VWSnZNRXltNmdwKzUrdWdPCm9pK0pOengwMzZnRHhGU3dOZSt5TUZUYXFoT2w1S2I3TXhmT2F2TWFyNXFWTXF4cU1nTzBDbUwyYzFGcGEwNGEKd01hUEROakdXbEd3cUZsVmNrZFBHbGVQaXJRakVvVWxBa2tDVFRkbFRWdVdCbUtOdDhXdGY5OGxuRVQ4QXNvRwptZzB4ZWs2TTFDczB1TDM4aG1aNlFaZ2JtQkV5TnR6WjZ2clFmQXNMQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTS0ZzSVJEbnFzcHdtdkZuL0IKVENoU3A3Q1JCekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRWdpVEJvT3J5dXdkOEZySlM1YisxdUpVY25LRApFcy8zQll1Yy9CNUozaWRuUVpSZy9sR1pGQlRvR1BXNThRWDVMU0lTanlUK2Y1VnkxMkFZaXpESmszd2FaVmFJCjFvdlU3aUUvOVl0Mi9WL3RmTGpEa01ZZk91KzlleS9WdmFDR3k1UXFzWnpqdHBDUy9CV05XbXJhTEhZT1dYWE4KdUJBeTdIVFNwZ25GV3lINzRrc0NlR1k1WndsZGRpaXdZSkt6bUFDeFhIZmo0ZzFLOUVNUVYzOGlCRm1ReE1NbApmRHF6ak5uendKOW0xVFQwSDNESmNpSklNbDJsa0szM2hLaml3dVpSNmd4dUwxVnlCZnA1K3BkbCtkUlpORUpyClhBY3YwMlFRalJCdFc1TzcvRDJoRnhzK2FpeDVLeGdaWkowS3JyT0NSaXhQRG1pWjdlR21yUTVxTHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://api.c2aecf0.kyma.ondemand.com
contexts:
  - name: shoot--kyma--c2aecf0
    context:
      cluster: shoot--kyma--c2aecf0
      user: shoot--kyma--c2aecf0
users:
  - name: shoot--kyma--c2aecf0
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - get-token
          - '--oidc-issuer-url=https://kyma.accounts.ondemand.com'
          - '--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6'
          - '--oidc-extra-scope=email'
          - '--oidc-extra-scope=openid'
        command: kubectl-oidc_login
        installHint: |
          kubelogin plugin is required to proceed with authentication
          # Homebrew (macOS and Linux)
          brew install int128/kubelogin/kubelogin

          # Krew (macOS, Linux, Windows and ARM)
          kubectl krew install oidc-login

          # Chocolatey (Windows)
          choco install kubelogin
