apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloadstats-pv
  labels:
    app: downloadstats
spec:
  storageClassName: ''
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/mnt/db'
