apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloadstats-pvc
  labels:
    app: downloadstats
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
