apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloadstats-pvc
  labels:
    app: downloadstats
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
