apiVersion: v1
kind: Service
metadata:
  name: downloadstats-service
spec:
  selector:
    app: downloadstats
  ports:
    - port: 3000
      targetPort: 3000

       ory-oathkeeper-55bc798d68-hl5r4                                   3/3     Running            0          11d
kyma-system        ory-oathkeeper-55bc798d68-hxdf5                                   3/3     Running            0          11d
kyma-system        ory-oathkeeper-55bc798d68-p9p47
